# Generated by Django 4.1.4 on 2022-12-12 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "client_id",
                    models.IntegerField(
                        db_column="Client_id", primary_key=True, serialize=False
                    ),
                ),
                ("address", models.TextField(db_column="Address")),
                ("phone", models.CharField(db_column="Phone", max_length=20)),
                ("name", models.TextField(db_column="Name")),
                ("email", models.TextField(db_column="Email")),
                (
                    "orderedamount",
                    models.IntegerField(
                        blank=True, db_column="OrderedAmount", null=True
                    ),
                ),
            ],
            options={
                "db_table": "client",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_number",
                    models.IntegerField(
                        db_column="Department_number", primary_key=True, serialize=False
                    ),
                ),
                ("department_name", models.TextField(db_column="Department_name")),
            ],
            options={
                "db_table": "department",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "manager_service_number",
                    models.IntegerField(
                        db_column="Manager_service_number",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(db_column="Name")),
                ("phone", models.CharField(db_column="Phone", max_length=20)),
                ("email", models.TextField(db_column="Email")),
            ],
            options={
                "db_table": "manager",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "order_number",
                    models.IntegerField(
                        db_column="Order_number", primary_key=True, serialize=False
                    ),
                ),
                ("order_date", models.DateField(db_column="Order_date")),
                ("order_amount", models.IntegerField(db_column="Order_amount")),
                ("execution_date", models.DateField(db_column="Execution_date")),
            ],
            options={
                "db_table": "orders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "invoice_number",
                    models.IntegerField(
                        db_column="Invoice_number", primary_key=True, serialize=False
                    ),
                ),
                ("date_of_sale", models.DateField(db_column="Date_of_sale")),
                ("quantity", models.IntegerField(db_column="Quantity")),
                ("sale_amount", models.IntegerField(db_column="Sale_amount")),
            ],
            options={
                "db_table": "sale",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TypeOfCoffee",
            fields=[
                (
                    "coffee_code",
                    models.IntegerField(
                        db_column="Coffee_code", primary_key=True, serialize=False
                    ),
                ),
                ("coffee_type_name", models.TextField(db_column="Coffee_type_name")),
            ],
            options={
                "db_table": "type_of_coffee",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Coffee",
            fields=[
                (
                    "coffee_code",
                    models.OneToOneField(
                        db_column="Coffee_code",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="coffee.typeofcoffee",
                    ),
                ),
                ("coffee_name", models.TextField(db_column="Coffee_name")),
                (
                    "date_of_manufacture",
                    models.DateField(db_column="Date_of_manufacture"),
                ),
            ],
            options={
                "db_table": "coffee",
                "managed": False,
            },
        ),
    ]
